config/routes.rb
Rails.application.routes.draw do
  resources :trades
  root :to => "pages#home"

  resources :users, :only => [:new, :create, :index, :update, :home]
  resources :reviews
  resources :reservations
  resources :quotes
  resources :trades
  resources :charges

  get '/charges/new' => 'charges#new', :as => 'pay_charges'
  get '/users' => "users#index"
  get '/users/edit' => "users#edit", :as => 'edit_user'
  get '/users/:id' => "users#show", :as => 'user_profile'


  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

end

app/models/quote.rb
# == Schema Information
#
# Table name: quotes
#
#  id                 :integer          not null, primary key
#  reservation_id     :integer
#  user_id            :integer
#  quote_value        :string
#  start_time         :datetime
#  estimated_duration :string
#  comment            :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Quote < ActiveRecord::Base
  belongs_to :user
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:reservation_id, :user_id, :status, :quote_value, :start_time, :estimated_duration, :comment)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reservation_id %><br>
    <%= f.number_field :reservation_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :quote_value %><br>
    <%= f.text_field :quote_value %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :estimated_duration %><br>
    <%= f.text_field :estimated_duration %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Reservation</th>
      <th>User</th>
      <th>Quote value</th>
      <th>Start time</th>
      <th>Estimated duration</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.reservation_id %></td>
        <td><%= quote.user_id %></td>
        <td><%= quote.quote_value %></td>
        <td><%= quote.start_time %></td>
        <td><%= quote.estimated_duration %></td>
        <td><%= quote.comment %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reservation:</strong>
  <%= @quote.reservation_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @quote.user_id %>
</p>

<p>
  <strong>Quote value:</strong>
  <%= @quote.quote_value %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @quote.start_time %>
</p>

<p>
  <strong>Estimated duration:</strong>
  <%= @quote.estimated_duration %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @quote.comment %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>