config/routes.rb
Rails.application.routes.draw do
  resources :trades
  root :to => "pages#home"

  resources :users, :only => [:new, :create, :index, :update, :home]
  resources :reviews
  resources :reservations
  resources :quotes
  resources :trades
  resources :charges

  get '/charges/new' => 'charges#new', :as => 'pay_charges'
  get '/users' => "users#index"
  get '/users/edit' => "users#edit", :as => 'edit_user'
  get '/users/:id' => "users#show", :as => 'user_profile'


  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

end

app/views/layouts/DEPRICARED_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TradieFind</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
        <div class="navbar-header">
        TradieFind
        </div>
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Home", root_path %></li>
            <% if @current_user.present? && @current_user.admin.present? %>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if @current_user.present? %>
                <li><%= link_to "Edit profile", edit_user_path(@current_user) %></li>
                <li><%= link_to "Logout #{ @current_user.email}", login_path, :method => :delete %></li>
            <% else %>
            <li><span class="signup-li glyphicon glyphicon-user">   <%= link_to "Sign up", 'users/new' %></span></li>
            <li><span class="signup-li glyphicon glyphicon-log-in">   <%= link_to "Login", login_path %></span></li>
            <% end %>
          </ul>

      </nav>

      <% if flash[:error].present? %>
    <h2 class="error errorMsg">
      <%= flash[:error] %>
    </h2>
      <% end %>

<%= yield %>

</body>
</html>

app/views/layouts/_footer.html.erb
<div class="container">

  <footer class="footer">
<% if params[:action] == "home" %>
    <div class="homeIndexContent">
      <div class="benefits">
       <h2> Benefits Of Using TradieFind </h2>
       <li> No more searching through Yellow Pages or Local Papers.</li>
       <li> No more ringing around chasing tradespeople. </li>
       <li> No more unreturned phone calls or worse ‘NO SHOWS’ </li>
       <li> More Free time at your disposal </li>
       <li> Single Point Of Contact</li>
       <%= image_tag ("tradie.jpg"), :class => "img1"%>
     </div>
     <div class="howWork">
       <h2> How It Works </h2>
       <li> 1. Contact us with your job requirements. </li>
       <li> 2. We will forward your request to the appropriate contractor/s.</li>
       <li> 3. They will contact you to arrange a quote.</li>
       <%= image_tag ("customersati.jpg"), :class => "img2" %>
     </div>
   </div>
   <% end %>

    <h6 id="copyright">
       copyright &copy; TradieFind 2016
    </h6>

  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">
        &#215;
      </a>
      <p><%=  content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%></p>
    </div>


<%end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <li class="navbar-brand">TradieFind</li>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %><span class="sr-only">(current)</span></li>
        <% if logged_in? %>
        <li><%= link_to "FAQ", "#faq" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">View <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Your Reservations", "#reservations/1" %></li>
            <li><%= link_to "Your Quotes", "#quotes" %></li>
            <li><%= link_to "Your Reviews", "#reviews" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Terms & Conditions", "#policy" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Archive", "#archive" %></li>
          </ul>
          <li><%= link_to "Contact Us", "#contactUs" %></li>
        </li>
        <% end %>
      </ul>
      <div id="search"></div>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li id="username">
              <%if (current_user.trade =="" || current_user.trade == "customer") %>
                 <i class="fa fa-money" aria-hidden="true"> </i>
               <%else  %>
                 <i class="fa fa-gavel" aria-hidden="true"></i>
              <% end %>
              <%= current_user.first_name %>
            </li>
          <li> <%= link_to "log out", logout_path, method: :delete %> </li>
          <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Account  <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "View Profile", "#user" %></li>
                      <li><%= link_to "Edit Profile", "#edituser" %></li>
                      <li role="separator" class="divider"></li>
                      <li><%= link_to "Pay Invoice", "#payment" %></li>

                    </ul>
            </li>
        <% else %>
          <li> <%= link_to "log in", login_path %>  </li>
          <li> <%= link_to "Sign up", new_user_path %>  </li>

        <%end  %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TradieFind</title>
  <link href='https://fonts.googleapis.com/css?family=PT+Sans+Narrow' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

      <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
  <div class="container">
      <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>